---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - wget
      - openssh-server
      - snapd
    state: present

- name: Ensure ssh service enabled and running
  ansible.builtin.systemd:
    name: ssh
    enabled: true
    state: started

- name: Ensure snapd service enabled and running
  ansible.builtin.systemd:
    name: snapd
    enabled: true
    state: started

- name: Install Visual Studio Code via Snap
  community.general.snap:
    name: code
    classic: true
    state: present

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: true
