services:
  comfyui:
    image: yanwk/comfyui-boot:cu130-slim-v2
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "8188:8188"
    environment:
      - CLI_ARGS=--disable-xformers --disable-smart-memory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - comfyui_root:/root
      - comfyui_models:/root/ComfyUI/models
      - comfyui_hf_hub:/root/.cache/huggingface/hub
      - comfyui_torch_hub:/root/.cache/torch/hub
      - comfyui_input:/root/ComfyUI/input
      - comfyui_output:/root/ComfyUI/output
      - comfyui_workflows:/root/ComfyUI/user/default/workflows
    networks:
      - local

  tts:
    image: domoskanonos/quisy-tts:0.39.1
    #image: quisy-tts:latest
    container_name: tts
    restart: unless-stopped
    ports:
      - "8045:8045"
    volumes:
      - tts_data:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DEVICE=cuda
      - MODEL_SIZE=1.7
    networks:
      - local

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      #- /home/laptop/Musik:/media/music:ro
      - /home/laptop/Musik:/media/music:ro
    networks:
      - local

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - immich_data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD:-postgres}
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-database
      - REDIS_HOSTNAME=immich-redis
      - IMMICH_LOG_LEVEL=${IMMICH_LOG_LEVEL:-log}
      - IMMICH_ALLOW_SETUP=${IMMICH_ALLOW_SETUP:-true}
    ports:
      - '2283:2283'
    depends_on:
      immich-redis:
        condition: service_started
      immich-database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - local

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - immich_model_cache:/cache
    environment:
      - DB_PASSWORD=${IMMICH_DB_PASSWORD:-postgres}
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-database
    restart: unless-stopped
    networks:
      - local

  immich-redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: unless-stopped
    networks:
      - local

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD:-postgres}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
      - DB_STORAGE_TYPE=${DB_STORAGE_TYPE:-SSD}
    volumes:
      - immich_postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
    healthcheck:
      test: pg_isready --dbname=immich --username=postgres || exit 1
      interval: 10s
      start_period: 30s
    networks:
      - local

  dozzle:
    image: docker.io/amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "8002:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - local

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN='3,33'
    networks:
      - local

volumes:
  comfyui_root:
  comfyui_models:
  comfyui_hf_hub:
  comfyui_torch_hub:
  comfyui_input:
  comfyui_output:
  comfyui_workflows:
  tts_data:
  jellyfin_config:
  jellyfin_cache:
  immich_data:
  immich_model_cache:
  immich_postgres_data:
  freshrss_data:
  freshrss_extensions:

networks:
  local:
