services:
  comfyui:
    image: yanwk/comfyui-boot:cu130-slim-v2
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "8188:8188"
    environment:
      - CLI_ARGS=--disable-xformers --disable-smart-memory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - comfyui_root:/root
      - comfyui_models:/root/ComfyUI/models
      - comfyui_hf_hub:/root/.cache/huggingface/hub
      - comfyui_torch_hub:/root/.cache/torch/hub
      - comfyui_input:/root/ComfyUI/input
      - comfyui_output:/root/ComfyUI/output
      - comfyui_workflows:/root/ComfyUI/user/default/workflows
    networks:
      - local

  tts:
    image: domoskanonos/quisy-tts:0.39.1
    #image: quisy-tts:latest
    container_name: tts
    restart: unless-stopped
    ports:
      - "8045:8045"
    volumes:
      - tts_data:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DEVICE=cuda
      - MODEL_SIZE=1.7
    networks:
      - local

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /media:/media:ro
    networks:
      - local

volumes:
  comfyui_root:
  comfyui_models:
  comfyui_hf_hub:
  comfyui_torch_hub:
  comfyui_input:
  comfyui_output:
  comfyui_workflows:
  tts_data:
  jellyfin_config:
  jellyfin_cache:

networks:
  local:
